# Generated by Django 4.2 on 2024-11-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EscuelasMov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('pagina_web', models.CharField(max_length=201)),
                ('pais', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarrerasInter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=False)),
                ('carreras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_inter', to='intercambio.carreras')),
                ('escuelas_mov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras_inter', to='intercambio.escuelasmov')),
            ],
        ),
    ]
